@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Mar 16 01:50:56 -0700 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 4f0348c0be21492dba2eed15887de047 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot top_TB_behav xil_defaultlib.top_TB -log elaborate.log"
call xelab  -wto 4f0348c0be21492dba2eed15887de047 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot top_TB_behav xil_defaultlib.top_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
